
### get product  index
GET http://localhost:3000/products.json

### post products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "better_napkins V",
  "price": 5,
 "description": "wipes spills",
 "image_url": "https://t3.ftcdn.net/jpg/05/00/80/80/240_F_500808027_ifTfsf5LxuErtDjGnA1IopwF6B0ITQPT.jpg",
 "quantity": 10
}

### get products show
GET http://localhost:3000/products/6.json

### patch products update
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
  "name": "improved_oil_heater"
}

### delete products destroy
DELETE http://localhost:3000/products/12


