
### get product  index
GET http://localhost:3000/products.json

### post products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "better_napkins VIII",
  "price": 5,
 "description": "wipes spills",
"supplier_id": 2,
 "quantity": 10
}

### post orders create
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "name": "better_napkins VIII",
  "price": 5,
 "description": "wipes spills",
"supplier_id": 2,
 "quantity": 10,
}
### get products show
GET http://localhost:3000/products/16.json

### patch products update
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
  "name": "improved_oil_heater"
}

### delete products destroy
DELETE http://localhost:3000/products/12

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test name",
  "email": "test@test.com",
 "password": "password",
"password_confirmation": "password"
}

